name: Python Static Analysis and Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install autopep8 pylint bandit pytest

      # AutoPEP8
      - name: Run AutoPEP8 and set status
        run: |
          autopep8 --in-place --aggressive --aggressive hw2_debugging.py rand.py
          echo "AUTOPEP_STATUS=$?" >> $GITHUB_ENV
      
      # Pylint
      - name: Run Pylint and set score
        run: |
          PYLINT_SCORE=$(pylint hw2_debugging.py rand.py --score=n | tail -n 1 | grep -o -E '[0-9]+\.[0-9]+')
          echo "PYLINT_SCORE=$PYLINT_SCORE" >> $GITHUB_ENV

      # Bandit
      - name: Run Bandit and set status
        run: |
          bandit hw2_debugging.py rand.py
          echo "BANDIT_STATUS=$?" >> $GITHUB_ENV

      # Pytest
      - name: Run Pytest and set status
        run: |
          pytest
          echo "PYTEST_STATUS=$?" >> $GITHUB_ENV

      # Create Pylint Badge
      - name: Create Pylint Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: <gist-ID>
          filename: pylint.json
          label: Pylint Score
          message: ${{ env.PYLINT_SCORE }}
          valColorRange: ${{ env.PYLINT_SCORE }}
          maxColorRange: 10
          minColorRange: 0

      # Create AutoPEP8 Badge
      - name: Create AutoPEP8 Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: <gist-ID>
          filename: autopep8.json
          label: AutoPEP8 Format
          message: ${{ env.AUTOPEP_STATUS }}
          valColorRange: ${{ env.AUTOPEP_STATUS }}
          maxColorRange: 0
          minColorRange: 1

      # Create Bandit Badge
      - name: Create Bandit Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: <gist-ID>
          filename: bandit.json
          label: Bandit Security
          message: ${{ env.BANDIT_STATUS }}
          valColorRange: ${{ env.BANDIT_STATUS }}
          maxColorRange: 0
          minColorRange: 1

      # Create Pytest Badge
      - name: Create Pytest Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: <gist-ID>
          filename: pytest.json
          label: Pytest Results
          message: ${{ env.PYTEST_STATUS }}
          valColorRange: ${{ env.PYTEST_STATUS }}
          maxColorRange: 0
          minColorRange: 1
