# .github/workflows/ci.yml

name: Python Static Analysis and Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.0-rc.1'

    - name: Install dependencies
      run: |
        pip install autopep8 pylint pyright pytest

    - name: Autopep8 (Auto format code)
      run: |
        autopep8 --in-place --aggressive --aggressive hw2_debugging.py rand.py

    - name: Run Pylint (Static analysis)
      run: |
        pylint hw2_debugging.py rand.py
        exit_code=$?
        if [ $exit_code -eq 0 ]; then
          echo "PYLINT_STATUS=Pass" >> $GITHUB_ENV
        else
          echo "PYLINT_STATUS=Fail" >> $GITHUB_ENV
        fi
        
    - name: Create Pylint Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: eda49634ad4b5d5f829e8ade4d6f138c
        filename: pylint.json
        label: Pylint
        message: ${{ env.PYLINT_STATUS }}
        color: ${{ env.PYLINT_STATUS == 'Pass' && 'green' || 'red' }}

    - name: Run pyright (Style check)
      run: |
        pyright hw2_debugging.py rand.py

    - name: Run Tests with pytest
      run: |
        pytest
